apiVersion: v1
kind: Secret
metadata:
  name: {{ template "schema-registry.fullname" . }}
type: Opaque
data:
  client-user: {{ .Values.sasl.scram.clientUser | b64enc | quote }}
  {{- if .Values.sasl.scram.clientPassword }}
  client-password: {{ .Values.sasl.scram.clientPassword | b64enc | quote  }}
  {{- else }}
  client-password: {{ randAlphaNum 10 | b64enc | quote  }}
  {{- end }}
  zookeeper-client-user: {{ .Values.sasl.scram.zookeeperClientUser | b64enc | quote }}
  {{- if .Values.sasl.scram.zookeeperClientPassword }}
  zookeeper-client-password: {{ .Values.sasl.scram.zookeeperClientPassword | b64enc | quote  }}
  {{- else }}
  zookeeper-client-password: {{ randAlphaNum 10 | b64enc | quote  }}
  {{- end }}
