apiVersion: v1
description: Apache Kafka is publish-subscribe messaging rethought as a distributed
  commit log. This is a UST Global Managed Catalog
name: kafka
version: 0.7.4
appVersion: 4.0.1
keywords:
- kafka
- zookeeper
- kafka statefulset
home: https://kafka.apache.org/
sources:
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
- https://github.com/Yolean/kubernetes-kafka
- https://github.com/confluentinc/cp-docker-images
- https://github.com/apache/kafka
maintainers:
- name: Ravikumar Sanjay Muthiyalu
  email: ravsanmut@gmail.com
icon: https://github.com/muthiyalu/ranchercatalog/blob/master/kafka--ust-logo.png
