dependencies:
- name: zookeeper
  version: 0.5.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: zookeeper.enabled
- name: kafka-topics-ui
  version: 0.1.0
  condition: kafka-topics-ui.enabled
- name: kafka-topics-ui
  version: 0.1.0
  condition: kafka-topics-ui.enabled
- name: schema-registry
  version: 0.4.3
  condition: schema-registry.enabled
- name: kafka-rest
  version: 0.1.0
  condition: kafka-rest.enabled
